name: easy_onvif
version: 2.1.2+13
homepage: https://github.com/faithoflifedev/easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
repository: https://github.com/faithoflifedev/easy_onvif
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  dio: ^5.2.1+1
  html_unescape: ^2.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sprintf: ^7.0.0
  universal_io: ^2.2.2
  uuid: ^4.3.3
  xml: ^6.3.0
  xml2json: ^6.1.0
  yaml: ^3.1.2
dev_dependencies:
  build_runner: ^2.4.5
  grinder: ^0.9.4
  json_serializable: ^6.7.0
  lints: ^2.1.1
  mustache_template: ^2.0.0
  process_run: ^0.13.0
  pub_semver: ^2.1.4
  publish_tools: ^0.1.0+10
  pubspec: ^2.3.0
  test: ^1.24.3
executables:
  onvif:
